# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Build Client PKG

on:
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.15.0
      - run: npm install -g yarn@1.22.19

  build-mac:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v3
      - run: yarn install
      - run: rm -rf build
      - run: yarn dist:production_mac

  upload-mac:
    runs-on: ubuntu-latest
    needs: build-mac
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - run: echo "::set-env name=PACKAGE_VERSION::$(node -p "require('./package.json').version")"
      - name: Upload mac pkg
        uses: actions/upload-artifact@v3.1.3
        with: 
          name: vikadata-$PACKAGE_VERSION.zip
          path: build
